name: Release Build

on:
  push:
    branches: [ master, release-* ]
  pull_request:
    branches: [ master, release-* ]

jobs:
  build:

    runs-on: windows-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-build]')"

    steps:
    - name: Generate BuildNumber
      id: version
      shell: pwsh
      run: echo "version=$(date +%Y.%-m).${env:GITHUB_RUN_NUMBER}" >> ${env:GITHUB_OUTPUT}
    - uses: actions/checkout@v3
    - name: Install Squirrel
      id: squirrel
      run: nuget install Clowd.Squirrel -version 2.9.40 -ExcludeVersion -OutputDirectory "./squirrel"
    - name: Build
      id: Build
      run: dotnet publish ./TextBlaster/TextBlaster.csproj --output ./TextBlaster/publish --configuration Release -r win10-x64 /p:Version=${{steps.version.outputs.version}} /p:PublishSingleFile=true --self-contained
    - name: Pack
      run: ./squirrel/Clowd.Squirrel/tools/Squirrel.exe pack --packId TextBlaster --packVersion ${{steps.version.outputs.version}} --packDir ./TextBlaster/publish --icon ./TextBlaster/applicationicon.ico
    - name: Create Release
      if: startsWith(github.ref, 'refs/heads/release-')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.version.outputs.version}}
        target_commitish: ${{github.ref}}
        body:
        draft: false
        prerelease: true
        files: ./Releases/*
